//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFinanceiro.CORE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControleFinanceiro.CORE.Resources.GlobalsResource", typeof(GlobalsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controle Financeiro.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controle Financeiro © 2012.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string GroupTypeCustomer {
            get {
                return ResourceManager.GetString("GroupTypeCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvedor.
        /// </summary>
        public static string GroupTypeDeveloper {
            get {
                return ResourceManager.GetString("GroupTypeDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerente.
        /// </summary>
        public static string GroupTypeManager {
            get {
                return ResourceManager.GetString("GroupTypeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Owner.
        /// </summary>
        public static string GroupTypeProductOwner {
            get {
                return ResourceManager.GetString("GroupTypeProductOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum Master.
        /// </summary>
        public static string GroupTypeScrumMaster {
            get {
                return ResourceManager.GetString("GroupTypeScrumMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador do sistema.
        /// </summary>
        public static string GroupTypeSystemAdministrator {
            get {
                return ResourceManager.GetString("GroupTypeSystemAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tester.
        /// </summary>
        public static string GroupTypeTester {
            get {
                return ResourceManager.GetString("GroupTypeTester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string GroupTypeUser {
            get {
                return ResourceManager.GetString("GroupTypeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acima da média.
        /// </summary>
        public static string PriorityLevelAboveAverage {
            get {
                return ResourceManager.GetString("PriorityLevelAboveAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acima do normal.
        /// </summary>
        public static string PriorityLevelAboveNormal {
            get {
                return ResourceManager.GetString("PriorityLevelAboveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Média.
        /// </summary>
        public static string PriorityLevelAverage {
            get {
                return ResourceManager.GetString("PriorityLevelAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critíca.
        /// </summary>
        public static string PriorityLevelCritical {
            get {
                return ResourceManager.GetString("PriorityLevelCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta.
        /// </summary>
        public static string PriorityLevelHigh {
            get {
                return ResourceManager.GetString("PriorityLevelHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altissíma.
        /// </summary>
        public static string PriorityLevelHighest {
            get {
                return ResourceManager.GetString("PriorityLevelHighest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baixa.
        /// </summary>
        public static string PriorityLevelLow {
            get {
                return ResourceManager.GetString("PriorityLevelLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mais baixa.
        /// </summary>
        public static string PriorityLevelLowest {
            get {
                return ResourceManager.GetString("PriorityLevelLowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem prioridade.
        /// </summary>
        public static string PriorityLevelNone {
            get {
                return ResourceManager.GetString("PriorityLevelNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string PriorityLevelNormal {
            get {
                return ResourceManager.GetString("PriorityLevelNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgente.
        /// </summary>
        public static string PriorityLevelUrgent {
            get {
                return ResourceManager.GetString("PriorityLevelUrgent", resourceCulture);
            }
        }
    }
}
