//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFinanceiro.CORE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControleFinanceiro.CORE.Resources.MessagesResource", typeof(MessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao tentar validar os dados..
        /// </summary>
        public static string AccountFormAutenticationErrorMessage {
            get {
                return ResourceManager.GetString("AccountFormAutenticationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilize seu nome de usuário e senha para acessar o sistema..
        /// </summary>
        public static string AccountSignInMessage {
            get {
                return ResourceManager.GetString("AccountSignInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro!.
        /// </summary>
        public static string AnErrorOccurred {
            get {
                return ResourceManager.GetString("AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A coleção &quot;{0}&quot; está vazia..
        /// </summary>
        public static string CheckArgumentsThrowIfEmptyCollection {
            get {
                return ResourceManager.GetString("CheckArgumentsThrowIfEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo &quot;{0}&quot; não é assinado pelo tipo &quot;{1}&quot;..
        /// </summary>
        public static string CheckArgumentsThrowIfNotAssignable {
            get {
                return ResourceManager.GetString("CheckArgumentsThrowIfNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de &quot;{0}&quot; não é um enumerador válido..
        /// </summary>
        public static string CheckArgumentsThrowIfNotEnumType {
            get {
                return ResourceManager.GetString("CheckArgumentsThrowIfNotEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O argumento &quot;{0}&quot; é nulo..
        /// </summary>
        public static string CheckArgumentsThrowIfNull {
            get {
                return ResourceManager.GetString("CheckArgumentsThrowIfNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cadeia de caracteres &quot;{0}&quot; é nula, vazia ou apenas espaços em branco..
        /// </summary>
        public static string CheckArgumentsThrowIfStringNotSafe {
            get {
                return ResourceManager.GetString("CheckArgumentsThrowIfStringNotSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique aqui para maiores informações..
        /// </summary>
        public static string ClickHereForMoreInformation {
            get {
                return ResourceManager.GetString("ClickHereForMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome de usuário não existe ou senha está incorreta..
        /// </summary>
        public static string CouldNotAuthenticateUser {
            get {
                return ResourceManager.GetString("CouldNotAuthenticateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi especificado um identificador para a entidade..
        /// </summary>
        public static string EmptyEntityIdentifierExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("EmptyEntityIdentifierExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A entidade não foi localizada na base de dados..
        /// </summary>
        public static string EntityNotFoundExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("EntityNotFoundExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A entidade foi removida com sucesso..
        /// </summary>
        public static string EntityWasDeletedWithSuccess {
            get {
                return ResourceManager.GetString("EntityWasDeletedWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, entre em contato com o suporte técnico e informe o erro, mencionando a mensagem e a hora..
        /// </summary>
        public static string ErrorTakeActionCourseLabel {
            get {
                return ResourceManager.GetString("ErrorTakeActionCourseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este valor é inválido..
        /// </summary>
        public static string InvalidFieldValueMessage {
            get {
                return ResourceManager.GetString("InvalidFieldValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criando instância do controlador &quot;{0}&quot;..
        /// </summary>
        public static string LOG_ControllerFactoryCreatingControllerInstance {
            get {
                return ResourceManager.GetString("LOG_ControllerFactoryCreatingControllerInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberando instância do controlador &quot;{0}&quot;..
        /// </summary>
        public static string LOG_ControllerFactoryReleasingControllerInstance {
            get {
                return ResourceManager.GetString("LOG_ControllerFactoryReleasingControllerInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um error desconhecido. Por favor, tente novamente..
        /// </summary>
        public static string UnknownErrorMessage {
            get {
                return ResourceManager.GetString("UnknownErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;Senha&quot; é obrigatório..
        /// </summary>
        public static string ValidateNonEmptyUserPassword {
            get {
                return ResourceManager.GetString("ValidateNonEmptyUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;Nome de usuário&quot; é obrigatório..
        /// </summary>
        public static string ValidateNonEmptyUserUsername {
            get {
                return ResourceManager.GetString("ValidateNonEmptyUserUsername", resourceCulture);
            }
        }
    }
}
