//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFinanceiro.CORE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControleFinanceiro.CORE.Resources.ValidationsResource", typeof(ValidationsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja existe um cadastro com este e-mail..
        /// </summary>
        public static string DuplicateEmailMessage {
            get {
                return ResourceManager.GetString("DuplicateEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este nome de usuário ja existe, utilize outro nome..
        /// </summary>
        public static string DuplicateUserNameMessage {
            get {
                return ResourceManager.GetString("DuplicateUserNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resposta para recuperação de senha não é valida..
        /// </summary>
        public static string InvalidAnswerMessage {
            get {
                return ResourceManager.GetString("InvalidAnswerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmação deve ser igual a senha digitada..
        /// </summary>
        public static string InvalidConfirmPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidConfirmPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário inserir uma data válida.
        /// </summary>
        public static string InvalidDateTimeMessage {
            get {
                return ResourceManager.GetString("InvalidDateTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor deve ser do tipo decimal (ex: 13,12)..
        /// </summary>
        public static string InvalidDecimalMessage {
            get {
                return ResourceManager.GetString("InvalidDecimalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este formato de e-mail é inválido..
        /// </summary>
        public static string InvalidEmailMessage {
            get {
                return ResourceManager.GetString("InvalidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve conter até {0} caracteres..
        /// </summary>
        public static string InvalidMaxLengthMessage {
            get {
                return ResourceManager.GetString("InvalidMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor deve ser numérico..
        /// </summary>
        public static string InvalidNumberMessage {
            get {
                return ResourceManager.GetString("InvalidNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter no mínimo {0} e no máximo {1} caracteres..
        /// </summary>
        public static string InvalidPasswordLengthMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha fornecida é inválida, entre com outra senha..
        /// </summary>
        public static string InvalidPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pergunta para recuperação de senha é inválida..
        /// </summary>
        public static string InvalidQuestionMessage {
            get {
                return ResourceManager.GetString("InvalidQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário uma identificação de usuário válida..
        /// </summary>
        public static string InvalidUserIdMessage {
            get {
                return ResourceManager.GetString("InvalidUserIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de usuário não é válido..
        /// </summary>
        public static string InvalidUserNameMessage {
            get {
                return ResourceManager.GetString("InvalidUserNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O provedor de autenticação retornou um erro, tente novamente..
        /// </summary>
        public static string ProviderErrorMessage {
            get {
                return ResourceManager.GetString("ProviderErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário informar uma Categoria..
        /// </summary>
        public static string RequiredCATEGORIAMessage {
            get {
                return ResourceManager.GetString("RequiredCATEGORIAMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar senha é obrigatório..
        /// </summary>
        public static string RequiredConfirmPasswordMessage {
            get {
                return ResourceManager.GetString("RequiredConfirmPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário informar uma conta..
        /// </summary>
        public static string RequiredCONTAMessage {
            get {
                return ResourceManager.GetString("RequiredCONTAMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail é obrigatório..
        /// </summary>
        public static string RequiredEmailMessage {
            get {
                return ResourceManager.GetString("RequiredEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        public static string RequiredNameMessage {
            get {
                return ResourceManager.GetString("RequiredNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova senha é obrigatório..
        /// </summary>
        public static string RequiredNewPasswordMessage {
            get {
                return ResourceManager.GetString("RequiredNewPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha antiga é obrigatória..
        /// </summary>
        public static string RequiredOldPasswordMessage {
            get {
                return ResourceManager.GetString("RequiredOldPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha é obrigatória..
        /// </summary>
        public static string RequiredPasswordMessage {
            get {
                return ResourceManager.GetString("RequiredPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário informar uma SubCategoria..
        /// </summary>
        public static string RequiredSUBCATEGORIAMessage {
            get {
                return ResourceManager.GetString("RequiredSUBCATEGORIAMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário definir um tipo de conta..
        /// </summary>
        public static string RequiredTipoContaMessage {
            get {
                return ResourceManager.GetString("RequiredTipoContaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário informar um tipo de pagamento..
        /// </summary>
        public static string RequiredTIPOPAGAMENTOMessage {
            get {
                return ResourceManager.GetString("RequiredTIPOPAGAMENTOMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome de usuário é obrigatório..
        /// </summary>
        public static string RequiredUserNameMessage {
            get {
                return ResourceManager.GetString("RequiredUserNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário informar um valor para este campo..
        /// </summary>
        public static string RequiredValueMessage {
            get {
                return ResourceManager.GetString("RequiredValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cadastro do usuário foi rejeitado. Verifique e tente novamente..
        /// </summary>
        public static string UserRejectedMessage {
            get {
                return ResourceManager.GetString("UserRejectedMessage", resourceCulture);
            }
        }
    }
}
